# Generated by Django 4.1.7 on 2024-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', 'time'], name='blog_BlogPo_author__bb7651_idx'),
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_BlogPosts',
        ),
    ]
